apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  ports:
  - port: 3100
    targetPort: 3100
    name: http
  - port: 9095
    targetPort: 9095
    name: grpc
  selector:
    app: loki
