apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"loki","namespace":"monitoring"},"spec":{"ports":[{"name":"http-metrics","port":3100,"targetPort":3100}],"selector":{"app":"loki"},"type":"ClusterIP"}}
  creationTimestamp: "2025-08-19T10:40:33Z"
  name: loki
  namespace: monitoring
  resourceVersion: "84694"
  uid: c286b46f-b554-4f8c-a6f1-fdb59a63bfc8
spec:
  clusterIP: 10.109.183.72
  clusterIPs:
  - 10.109.183.72
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app: loki
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
