apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app.kubernetes.io/name: promtail
spec:
  selector:
    app.kubernetes.io/name: promtail
  ports:
    - name: http
      port: 9080
      targetPort: http-metrics
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: loki
  ports:
    - port: 3100
      targetPort: http-metrics
