apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    
    positions:
      filename: /tmp/positions.yaml
    
    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
    
    scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:["default"]
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_name]
          action: keep
          regex: .+
        - source_labels: [__meta_kubernetes_pod_uid]
          target_label: __path__
          replacement: /var/log/pods/*$1/*.log
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
    - job_name: system
      static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/syslog
