apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "14"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{"deprecated.daemonset.template.generation":"13"},"creationTimestamp":"2025-08-18T20:38:04Z","generation":13,"name":"promtail","namespace":"monitoring","resourceVersion":"119783","uid":"80b7909e-53fe-4f38-b872-ce1c7679b410"},"spec":{"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/name":"promtail"}},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2025-08-20T10:10:28+01:00"},"creationTimestamp":null,"labels":{"app.kubernetes.io/name":"promtail"}},"spec":{"containers":[{"args":["-config.file=/etc/promtail/promtail-config.yaml"],"image":"grafana/promtail:2.9.1","imagePullPolicy":"IfNotPresent","name":"promtail","ports":[{"containerPort":9080,"name":"http-metrics","protocol":"TCP"}],"resources":{"requests":{"cpu":"100m","memory":"128Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/etc/promtail","name":"config"},{"mountPath":"/var/log","name":"varlog","readOnly":true},{"mountPath":"/var/log/flask","name":"flask-logs","readOnly":true}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":4,"runAsGroup":4,"runAsUser":0},"serviceAccount":"promtail","serviceAccountName":"promtail","terminationGracePeriodSeconds":30,"tolerations":[{"operator":"Exists"}],"volumes":[{"configMap":{"defaultMode":420,"name":"promtail-config"},"name":"config"},{"hostPath":{"path":"/var/log","type":""},"name":"varlog"},{"hostPath":{"path":"/var/log/flask","type":"DirectoryOrCreate"},"name":"flask-logs"}]}},"updateStrategy":{"rollingUpdate":{"maxSurge":0,"maxUnavailable":1},"type":"RollingUpdate"}},"status":{"currentNumberScheduled":3,"desiredNumberScheduled":3,"numberAvailable":3,"numberMisscheduled":0,"numberReady":3,"observedGeneration":13,"updatedNumberScheduled":3}}
  creationTimestamp: "2025-08-18T20:38:04Z"
  generation: 14
  name: promtail
  namespace: monitoring
  resourceVersion: "125174"
  uid: 80b7909e-53fe-4f38-b872-ce1c7679b410
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-08-20T10:10:28+01:00"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: promtail
    spec:
      containers:
      - args:
        - -config.file=/etc/promtail/promtail-config.yaml
        image: grafana/promtail:2.9.1
        imagePullPolicy: IfNotPresent
        name: promtail
        ports:
        - containerPort: 9080
          name: http-metrics
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/promtail
          name: config
        - mountPath: /var/log
          name: varlog
          readOnly: true
        - mountPath: /var/log/flask
          name: flask-logs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 4
        runAsGroup: 4
        runAsUser: 0
      serviceAccount: promtail
      serviceAccountName: promtail
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: promtail-config
        name: config
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/log/flask
          type: DirectoryOrCreate
        name: flask-logs
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  observedGeneration: 14
  updatedNumberScheduled: 3
